### PR TITLE
Generalize reshaping ideas from elm/earthio

### PR DESCRIPTION
**Pull request by PeterDSteinberg**
In early work on [`elm`](https://github.com/ContinuumIO/elm) and [`earthio`](https://github.com/ContinuumIO/earthio) we developed `ElmStore` (an `xarray.Dataset` subclass) and used `reshape.py` there to `flatten` `DataArrays` of an `ElmStore` from 2D rasters to columns as part of a `DataArray` in the returned `ElmStore` called `flat`.  This system had the following limitations:
 * `band_order` and spatial metadata had to be maintained in somewhat brittle manner in `.attrs` of an `ElmStore` for the reshaping from rasters to columns of feature matrix to work.  This PR fixes some of that and 
  * Improves the naming: `to_ml_features` is the new method that replaces `flatten` and `from_ml_features` takes a feature matrix back to a `Dataset` subclass instance that has raster `DataArrays
  * Removes hard coded names like `flat`
  * Uses `layer` instead of `band` (Fixes [elm issue 173](https://github.com/ContinuumIO/elm/issues/173))
  * Supports >2D (WIP) better (see also Elm Milestone on Data Structure Flexibility -
 https://github.com/ContinuumIO/elm/milestone/8)

More notes soon...

### CODE REVIEW

**Comment by PeterDSteinberg** [comment]
I'm going to address issue #4 within this PR.  sorry about large file diff, but it will give us test feedback here automatically for a few Python versions

**Comment by PeterDSteinberg** [comment]
Items we can address in this PR:
 * [ ] `conda.recipe` and `.travis.yml` were updated / added to address #4 but Travis CI has not been configured for this repo.  @gbrener please configure Travis CI to listen to events on this repo and see .travis.yml for env vars that are needed like the Earthio system
 * [ ] Needs more tests:
   * [ ] Look through the notebook examples and see if there is anything that needs to be tested better
   * [ ] Specifically one thing that needs to be tested: Call `to_features()` to convert to a flattened version of some rasters or N-D arrays, then assign NaN to some of the rows in the flattened 2-D array, then drop those NaN rows, then call `from_features` and ensure it can be reshaped back to the original N-D arrays or rasters despite having lost some rows.
* [ ] After PR 2 has some tests / examples, merge that one into master or into this one and make the following changes:
   * [ ] `to_ml_features` should be `to_features` - I simplified naming in this PR - see if you agree with new names and make changes to be consistent
  * [ ] This PR has some logic related to `astype` argument (e.g. return a DataFrame rather than Dataset or MLDataset).  PR 2 also has some `astype` logic.  This PR has the astype logic in a module `xarray_filters/astype.py` since we may or may not have different `astype` logic for different contexts and may need a couple functions related to that.
  * [ ] Take a general look for TODO in PR 3 and see if those can be addressed (likely after the bullet point above) or if the work should be deferred.  Many TODO's in there now relate to PR #2 / PR #3 consistency.

**Comment by gbrener** [comment]
@PeterDSteinberg, Travis-CI is now setup, and `pytest` is being run from `conda-build`. The tests are failing, however at this point we should be able to see once the tests start passing.

**Comment by PeterDSteinberg** [comment]
CI set up looks good - See if you can figure out why this [doctest is failing](https://travis-ci.org/ContinuumIO/xarray_filters/jobs/272167280#L1601) - that doctest just confirms that a `DataArray` can go from a features matrix into separate `DataArray` rasters in an `MLDataset` back into the same starting features 2-D `DataArray`.

**Comment by gpfreitas** [comment]
We just merged work from PR #2 into this PR.

Remaining work from that:

- write tests (hopefully will be easier with the work already done in this PR)
- clean up docs

**Pull request closed without merging**
