### PR TITLE
Unify PR 3 and PR 2 astype logic (converting Xarray - Pandas - Numpy)

### PR DESCRIPTION
**Pull request by PeterDSteinberg**
This is a clean up of #3 in a separate branch (changes in astype-related logic were large).

### CODE REVIEW

**Comment by gpfreitas** [comment]
Notes for future work, while this is fresh on my mind

- First order of the day for me is to merge the changes from f58f72dd471f130b38a49e106498ef5bb9ffad93
- Look for any other relevant work done in the reshape-pipe-experiments branch (see PR #3).

**Comment by gpfreitas** [comment]
@PeterDSteinberg 

I'm trying to merge my changes in `reshape-pipe-experiments` into this branch.

To do that, I'm trying to see how you changed `datasets.py` relative to the commit from that branch that you used as a base for your changes: commit 674ba07. So I ran

```bash
git diff -w --ignore-blank-lines 674ba07..ps-reshape-pipe-experiments -- datasets.py
```

Based on what I saw, the only changes to `datasets.py` were:

- Move `XyTransformer` to `astype.py`
- Rename `XyTransformer` to `NpXyTransformer`.

Then looking into `astype.py` (from this branch), I can see the last change:

- Refactor `NpXyTransformer` into two classes, `TypeTransformerBase` and `NpXyTransformer(TypeTransformerBase)`, where the base class just has the `__init__` and `astype` methods, and `astype` was "outsourced" to a standalone function.

Regarding this, I have one question:

- What were you trying to do by splitting XyTransformer into two classes and a standalone function? The previous design was already a bit complicated, and this one is yet more complicated. What do we gain by factoring out the initialization portion and the `astype` function?

Another thing that confused me, was this docstring for the standalone `astype` function in `astype.py`

```python
def astype(obj, to_type, **kwargs):
    """Convert to given type.

    self.astype(f, **kwargs) calls self.to_f(**kwargs)

    Valid types are in NpXyTransformer.accepted_types.

    See Also
    --------

    NpXyTransformer.to_dataset
    NpXyTransformer.to_array
    NpXyTransformer.to_dataframe
    NpXyTransformer.to_*
    MLDataset.to_dataset
    MLDataset.to_array
    MLDataset.to_dataframe
    MLDataset.to_*
    etc...
    """
```

I would imagine that instead of adding the lines

```
    MLDataset.to_dataset
    MLDataset.to_array
    MLDataset.to_dataframe
    MLDataset.to_*
```

you would add a single line

```
    NpXyTransformer.to_ml_dataset
```

As written, it seems that `MLDataset` is an alternative for `NpXyTransformer`. I thought `MLDataset` was an alternative to `xarray.Dataset`, `numpy.ndarray`, `pandas.DataFrame`, and as such, a target for a `to_*` transformation inside `NpXyTransformer`.

So my second and third questions are:

- is MLDataset supposed to be another "transformer type" object (like XyTransformer) or a data structure / container (like ndarray, dataset, dataframe)?
- If it seems I got this all wrong, can you clarify your intention?

**Comment by gpfreitas** [comment]
@PeterDSteinberg 

For context, I thought you hadn't touched the `datasets.py`. With the changes you made, it's not clear to me which one of the following mutually exclusive paths I should take:

- __Alternative 1:__ revert `datasets.py` back to what's in the latest commit of `reshape-pipe-experiments` (which is my latest version of `datasets.py`) and remove the `astype` function, `NpXyTransformer` and `TypeTransformerBase` from `astype.py`
- __Alternative 2:__  revert `datasets.py` back to what's in the latest commit of `reshape-pipe-experiments` (which is my latest version of `datasets.py`) and move `XyTransformer` to `astype.py` plus "replay your factoring", that is, split its functionality into two classes, `TypeTransformerBase` class, `NpXyTransformer` and the standalone `astype` function.
- Something else?

**Comment by gpfreitas** [comment]
Note: sorting the issue outlined in my two previous comments should allow me to merge my previous changes to the `reshape-pipe-experiments` branch and move on with this issue. It's the only blocker I can see now.

**Comment by PeterDSteinberg** [comment]
@gpfreitas Note that `class MLDataset(xr.Dataset, TypeTransformerBase)` uses the `TypeTransformerBase` as a mixin.  I'm open to either resolution - your call.  I separated `TypeTransformerBase` so that `def astype` could be inherited for each class.  

Also I moved `XyTransformer` from `datasets.py` because it is related to type conversion that may be of general utility, e.g. outside the context of synthetic data creators.

`MLDataset` is not analogous to `TypeTransformerBase` - the behavior of `MLDataset` is more like `xarray.Dataset` (see inheritance - maybe I have the order wrong - we want the `__init__` function of `xr.Dataset` if we go with this approach).  If it is more clear not to have `TypeTransformerBase`, then that's fine by me.

**Comment by gpfreitas** [comment]
From @PeterDSteinberg , on Flowdock:

>I commented there a bit ago - please solve in whatever way is convenient - I was working fast and late at night when I made those changes.
>
> The basic idea is that MLDataset's need to be converted to types as well.  Such as calling to_features and getting numpy arrays for X, y. where X is the .values of the layer called features and y is a column that is taken from .features using the yname argument.  I saw that your PR 2 introduced yname which I think is a good thing - to have one of the MLDataset layers be y, rather than passing 2-tuples or 3-tuples around.

**Comment by gpfreitas** [comment]
@PeterDSteinberg, @gbrener 

I just merged back everything I wanted from the `reshape-pipe-experiments` branch (old PR #3).

Please see the commit message from my last commit, 35e9516.

A few things that need to be done still in `NpXyTransformer`:

- doctests/examples for the methods `to_dataset` and `to_mldataset`.

As far as organization goes:

- Move `NpXyTransformer` to `astype.py`. Take care not to break references.

I can do those things early next week.

For emphasis: right now, `NpXyTransformer` only supports converting from NumPy arrays to other types (that was the usecase from sklearn). I can write more code to support transforming back. Once that happens, I think some kind of refactoring along the lines of what @PeterDSteinberg was doing on 1d9b2aa may be helpful (factoring out `astype` as a standalanoe function, for example).

**Comment by PeterDSteinberg** [comment]
Merged.  Test failures related to:
 * Failures in the `deploy` section (unrelated to the PR's code there is a failure on the `anaconda upload` of a built package on Python 3.5/3.6
 * Failure in the PR's code on Python 2.7 related to `inspect` methods in 2.7 vs 3.* 

I'll make separate issues for the two bullets above.

**Pull request merged**
